keys:
  - &hosts:
    - &konishi age18dqxcqq3zhl9r85zqdjnj2zqxudds7wae8gjctd6z5qcpafcxdxskq46s6
    - &polis age1easztw0jvh52z99a6qteesh3c6qg604344nxyf7wgwvtd4d44s2qkk0jq3
    - &carter-zimmerman age1y3zqpjp7uj97u0eskfy8gsck72vh5vwgjus8uv3gwnk8z2helpysvex66r
    - &conjoiner age1jyhl6dyx4xmec4e7qnjlc0edhjref7lshc35h8aarwvrvlycka3qjrdnj0
    - &pattern-juggler age14g8n233nk3p0grkhkfj8qhhnjwgerku98e9z28edr7vmenmzafdqwe8df6

creation_rules:
  - path_regex: machines/konishi/secrets.ya?ml$
    key_groups:
    - age:
      - *konishi
  - path_regex: machines/carter-zimmerman/secrets.ya?ml$
    key_groups:
    - age:
      - *carter-zimmerman
  - path_regex: machines/conjoiner/secrets.ya?ml$
    key_groups:
    - age:
      - *conjoiner
  - path_regex: machines/pattern-juggler/secrets.ya?ml$
    key_groups:
    - age:
      - *pattern-juggler
  - path_regex: machines/common/secrets.ya?ml$
    key_groups:
    - age:
      - *polis
      - *konishi
      - *carter-zimmerman
      - *conjoiner
      - *pattern-juggler
