# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, inputs, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  nixpkgs = {
    overlays = [ inputs.arc.overlays.arc ];
  };

  hardware = {
    nvidia = {
      package = pkgs.arc.packages.nvidia-patch.override {
        nvidia_x11 = config.boot.kernelPackages.nvidiaPackages.stable;
      };
      modesetting.enable = false;
    };
    opengl.enable = true;
  };

  boot = {
    initrd = {
      enable = true;
      availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usb_storage" "usbhid" "sd_mod" ];
      luks.devices."root" = {
        device = "/dev/disk/by-uuid/ac9334b2-e93c-45dc-a57d-1238ea1f1e7b";
        preLVM = true;
        allowDiscards = true;
      };
      kernelModules = [ "dm-snapshot" ];
    };
    kernelModules = [ "kvm-intel" ];
    #extraModulePackages = [ config.boot.kernelPackages.nvidia_x11 ];
    loader = {
      systemd-boot.enable = true;
      efi.efiSysMountPoint = "/boot";
      efi.canTouchEfiVariables = true;
    };
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/eef06cda-cded-4c4b-a063-4898edafe950";
      options = [ "noatime" "nodiratime" "discard" ];
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/674B-657A";
      fsType = "vfat";
    };

  fileSystems."/media" =
    {
      device = "/dev/disk/by-id/wwn-0x500003964b98123e-part2";
      fsType = "ntfs3";
      options = [ "rw" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/34a6de5d-fc30-4737-96cf-bc5b2cb9004d"; }];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
